### ISSUE TITLE
No transparency effects on inactive window (Windows 11)

### ISSUE THREAD

**Issue by TheColorman** [xirreal/Acrylic#12]
Upgrading from windows 10 to 11 I noticed that Acrylic is no longer working when the window is inactive (see [this very high quality gif](https://i.imgur.com/mE3oMxW.gif)). Seems like this [might be a windows limitation](https://learn.microsoft.com/en-us/windows/apps/design/style/acrylic#:~:text=In%20addition%2C%20only,on%20desktop%20deactivates), but in that case I don't see why it ever worked in windows 10. 
![the gif in question](https://i.imgur.com/mE3oMxW.gif)

**Comment by yellowsink** [comment]
![image](https://github.com/uwu/Acrylic/assets/19270622/87e10371-c5bc-4d6c-8cfc-32149e6a2f72)

i wonder if the window could be made transparent and in-app acrylic used

that or this is a new restriction and new docs reflect that (?)

**Comment by xirreal** [comment]
The old way to do acrylic was not documented by windows and was a hack, therefore the regular windows restrictions do not apply on windows 10 or 11 before 22H1. This is really not fixable as this hack was removed entirely.

**Comment by TheColorman** [comment]
> i wonder if the window could be made transparent and in-app acrylic used  

Definitely possible judging by [this](https://github.com/microsoft/terminal/issues/7158#issuecomment-668020748) comment on a similar Windows Terminal issue.  

> that or this is a new restriction and new docs reflect that (?)  

Again referring to that comment, this has apparently been an issue since mid-2020.

**Comment by xirreal** [comment]
We do not have the same flexibility as we are not using C#, .NET APIs or UWP APIs.

**Comment by TheColorman** [comment]
Damn, that sucks. Here's to hoping Microsoft adds an override or something.

**Comment by TheColorman** [comment]
> The old way to do acrylic was not documented by windows and was a hack, therefore the regular windows restrictions do not apply on windows 10 or 11 before 22H1. This is really not fixable as this hack was removed entirely.

Out of curiosity, when did the hack stop working? Cause I could have sworn I had the newest version of Win 10 before upgrading.

**Comment by xirreal** [comment]
on windows 11 22H1
