### ISSUE TITLE
Mica Material

### ISSUE THREAD

**Issue by Kyza** [xirreal/Acrylic#2]
Will this ever support [Windows 11's Mica material](https://docs.microsoft.com/en-us/windows/apps/design/style/mica)?

**Comment by xirreal** [comment]
Short answer, probably not.
Long answer, if its accessible with the Win32 API (which i doubt) then it's possible.

**Comment by Void48** [comment]
> Short answer, probably not. Long answer, if its accessible with the Win32 API (which i doubt) then it's possible.

there's now public Win32 API for Mica,Acrylic effects

**Comment by Void48** [comment]
DWMWA_SYSTEMBACKDROP_TYPE

**Comment by hyblocker** [comment]
I have implemented Mica and Acrylic in Amethyst Installer, so here are some reference links to the P/Invoke parts of it for enabling Mica.

Win32 APIs exist, see here for reference.
https://github.com/KinectToVR/Amethyst-Installer/blob/dc057620e600f4b832d42de0a76eae42d493a856/Amethyst-Installer/PInvoke/DWM.cs#L100-L142

Note that you also have to extend the window chrome for the Mica material to take effect.
https://github.com/KinectToVR/Amethyst-Installer/blob/dc057620e600f4b832d42de0a76eae42d493a856/Amethyst-Installer/MainWindow.xaml.cs#L102-L104

**Comment by hyblocker** [comment]
I'll additionally add that simply replacing `"arylic"` with `"mica"` when enabling the effect works. https://github.com/uwu/Acrylic/blob/4753ac0de7b5eef0a46026a09f238896dda8838c/app/index.js#L241

**Comment by xirreal** [comment]
I know already that replacing "acrylic" with "mica" works but i just haven't gotten around to adding the fallbacks for when it's not supported

**Comment by xirreal** [comment]
Added support in the latest commit. Cheers!
