### ISSUE TITLE
Windows 7 Support

### ISSUE THREAD

**Issue by ghost** [xirreal/Acrylic#5]
Hey I've never used GitHub so I apologize for the nature of this post.
I couldn't get Acrylic working on win7 because of an error stating that it's only supported on win10/11.

This code block in index.js is the issue:
`electron.ipcMain.on("enable", () => {`
`  console.log("[Acrylic] Enabling Acrylic.");`
`  vibe?.applyEffect?.(mainWindow, "acrylic");`
`});`
Specifically the last bit (mainWindow, "acrylic"). Changing "acrylic" to "blur", which is supported on win7 also throws an error, but removing the entire code block as pasted above makes everything work without issue.
I knows Windows 7 is far past EoL, but I hope this may help anyone else looking for support.

**Comment by xirreal** [comment]
Windows 7 composition effects work in a completely different way. Acrylic is only supported on Windows 10 or newer.
