### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by thesamgordon** [xirreal/Acrylic#6]
Hi,

I'm getting an error when opening Discord after installing Acrylic: 
![image](https://user-images.githubusercontent.com/51384418/205407271-8310fc99-8fd2-4971-a721-103d9ec499c6.png)

This error comes down to this line of code: `let originalAppPath = path.join(basePath, "original.asar");`

This file is no where to be found, is it missing? 

Thanks!

**Comment by xirreal** [comment]
Simply rename your app.asar to original.asar. This was done to supprt Canary versions of discord which will not load from the folder unless the asar is renamed

**Comment by thesamgordon** [comment]
Thanks for the help. I do think that this should be changed as most people do not use Discord Canary.
